url: https://gauravtan26.github.io
baseurl: ""
# Site settings
title: Gaurav Singh Tanwar
email: gstanwar26@gmail.com
description: "Data Scientist with a demonstrated history of solving business problems using machine learning and statistics. Skilled in NLP, Computer Vision, Python, Data Analysis, Statistical Modeling, Docker and Python. Developed and deployed machine learning applications using Docker and AWS. Considerable work experience with Keras and PyTorch Frameworks. Strong engineering professional with a Bachelor of Technology from Indian Institute of Technology, Delhi."


# Team names, titles and social links
people:
# - name: Kay Garland
#   pic: 1
#   position: Lead Designer
#   social:
#     - title: twitter
#       url: #
#     - title: facebook
#       url: #
#     - title: stack-overflow
#       url: #

- name: Gaurav Singh Tanwar
  pic: 2
  position: Data Scientist
  social:
    - title: linkedin
      url: https://www.linkedin.com/in/gauravsingh26/
    - title: github
      url: https://github.com/gauravtan26
    - title: medium
      url: https://gauravtanwar1.medium.com/

# - name: Diana Petersen
#   pic: 3
#   position: Lead Developer
#   social:
#     - title: twitter
#       url: #
#     - title: facebook
#       url: #
#     - title: google-plus
#       url: #

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: linkedin
    url: https://www.linkedin.com/in/gauravsingh26/
  - title: github
    url: https://github.com/gauravtan26
  - title: medium
    url: https://gauravtanwar1.medium.com/

# Postal address (add as many lines as necessary)
address:
  - line: South Delhi, Delhi
  - line: India

# Build settings
markdown: kramdown
permalink: pretty